create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list eth_udp_loop_inst/u_gmii_to_rgmii/u_rgmii_rx/gmii_tx_clk]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {eth_udp_loop_inst/u_udp/u_udp_tx/tx_data[0]} {eth_udp_loop_inst/u_udp/u_udp_tx/tx_data[1]} {eth_udp_loop_inst/u_udp/u_udp_tx/tx_data[2]} {eth_udp_loop_inst/u_udp/u_udp_tx/tx_data[3]} {eth_udp_loop_inst/u_udp/u_udp_tx/tx_data[4]} {eth_udp_loop_inst/u_udp/u_udp_tx/tx_data[5]} {eth_udp_loop_inst/u_udp/u_udp_tx/tx_data[6]} {eth_udp_loop_inst/u_udp/u_udp_tx/tx_data[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {udp_tx_control_inst/rd_data_i[0]} {udp_tx_control_inst/rd_data_i[1]} {udp_tx_control_inst/rd_data_i[2]} {udp_tx_control_inst/rd_data_i[3]} {udp_tx_control_inst/rd_data_i[4]} {udp_tx_control_inst/rd_data_i[5]} {udp_tx_control_inst/rd_data_i[6]} {udp_tx_control_inst/rd_data_i[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 5 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {udp_tx_control_inst/arbitr_result[0]} {udp_tx_control_inst/arbitr_result[1]} {udp_tx_control_inst/arbitr_result[2]} {udp_tx_control_inst/arbitr_result[3]} {udp_tx_control_inst/arbitr_result[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list udp_tx_control_inst/rd_data_vld_i]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list eth_udp_loop_inst/u_udp/u_udp_tx/tx_done]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list eth_udp_loop_inst/u_udp/u_udp_tx/tx_req]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets SFPGA_RGMII_TX_CLK_OBUF]
