create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list eth_udp_loop_inst/u_gmii_to_rgmii/u_rgmii_rx/BUFG_inst_0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {eth_udp_loop_inst/u_udp/u_udp_tx/tx_data[0]} {eth_udp_loop_inst/u_udp/u_udp_tx/tx_data[1]} {eth_udp_loop_inst/u_udp/u_udp_tx/tx_data[2]} {eth_udp_loop_inst/u_udp/u_udp_tx/tx_data[3]} {eth_udp_loop_inst/u_udp/u_udp_tx/tx_data[4]} {eth_udp_loop_inst/u_udp/u_udp_tx/tx_data[5]} {eth_udp_loop_inst/u_udp/u_udp_tx/tx_data[6]} {eth_udp_loop_inst/u_udp/u_udp_tx/tx_data[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 16 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {message_comm_inst/message_comm_rx_inst/rx_start_num_sync[0]} {message_comm_inst/message_comm_rx_inst/rx_start_num_sync[1]} {message_comm_inst/message_comm_rx_inst/rx_start_num_sync[2]} {message_comm_inst/message_comm_rx_inst/rx_start_num_sync[3]} {message_comm_inst/message_comm_rx_inst/rx_start_num_sync[4]} {message_comm_inst/message_comm_rx_inst/rx_start_num_sync[5]} {message_comm_inst/message_comm_rx_inst/rx_start_num_sync[6]} {message_comm_inst/message_comm_rx_inst/rx_start_num_sync[7]} {message_comm_inst/message_comm_rx_inst/rx_start_num_sync[8]} {message_comm_inst/message_comm_rx_inst/rx_start_num_sync[9]} {message_comm_inst/message_comm_rx_inst/rx_start_num_sync[10]} {message_comm_inst/message_comm_rx_inst/rx_start_num_sync[11]} {message_comm_inst/message_comm_rx_inst/rx_start_num_sync[12]} {message_comm_inst/message_comm_rx_inst/rx_start_num_sync[13]} {message_comm_inst/message_comm_rx_inst/rx_start_num_sync[14]} {message_comm_inst/message_comm_rx_inst/rx_start_num_sync[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 5 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {udp_tx_control_inst/arbitr_result[0]} {udp_tx_control_inst/arbitr_result[1]} {udp_tx_control_inst/arbitr_result[2]} {udp_tx_control_inst/arbitr_result[3]} {udp_tx_control_inst/arbitr_result[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list udp_tx_control_inst/rd_data_vld_noclear]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list message_comm_inst/message_comm_rx_inst/rx_start_sync]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list udp_tx_control_inst/sfpga_comm_clear]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list udp_tx_control_inst/slave_tx_empty]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list eth_udp_loop_inst/u_udp/u_udp_tx/tx_done]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list udp_tx_control_inst/tx_instruct_empty]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list eth_udp_loop_inst/u_udp/u_udp_tx/tx_req]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list clk_wiz_inst/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 16 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {message_comm_inst/message_comm_rx_inst/comm_rx_data_num[0]} {message_comm_inst/message_comm_rx_inst/comm_rx_data_num[1]} {message_comm_inst/message_comm_rx_inst/comm_rx_data_num[2]} {message_comm_inst/message_comm_rx_inst/comm_rx_data_num[3]} {message_comm_inst/message_comm_rx_inst/comm_rx_data_num[4]} {message_comm_inst/message_comm_rx_inst/comm_rx_data_num[5]} {message_comm_inst/message_comm_rx_inst/comm_rx_data_num[6]} {message_comm_inst/message_comm_rx_inst/comm_rx_data_num[7]} {message_comm_inst/message_comm_rx_inst/comm_rx_data_num[8]} {message_comm_inst/message_comm_rx_inst/comm_rx_data_num[9]} {message_comm_inst/message_comm_rx_inst/comm_rx_data_num[10]} {message_comm_inst/message_comm_rx_inst/comm_rx_data_num[11]} {message_comm_inst/message_comm_rx_inst/comm_rx_data_num[12]} {message_comm_inst/message_comm_rx_inst/comm_rx_data_num[13]} {message_comm_inst/message_comm_rx_inst/comm_rx_data_num[14]} {message_comm_inst/message_comm_rx_inst/comm_rx_data_num[15]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list message_comm_inst/message_comm_rx_inst/rx_sync_result]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets tp100_OBUF]
